# Name of the automated job
name: Fetch Latest FIRMS Data

# Controls when the action will run
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  build:
    runs-on: ubuntu-latest

    # --- THIS IS THE NEW PART TO ADD ---
    # Grant the action permission to write to the repository
    permissions:
      contents: write
    # ------------------------------------

    # Steps represent a sequence of tasks
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Download latest FIRMS KMZ
        run: |
          curl "https://firms.modaps.eosdis.nasa.gov/api/kml_fire_footprints/usa_contiguous_and_hawaii/24h/noaa-21-viirs-c2/FirespotArea_usa_contiguous_and_hawaii_noaa-21-viirs-c2_24h.kmz" -o FirespotArea_J2_VIIRS_C2_USA_contiguous_and_Hawaii_24h.kmz
          
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Updated FIRMS fire data"
          file_pattern: "*.kmz"
